In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_json("../src/tracker/candles_1h.jsonl",lines=True,encoding="utf-8")

In [27]:
df.head()

,time,symbol,open,high,low,close,volume
0,2025-08-11T09:00:00+00:00,BTC-USD,121662.15,121703.75,121094.37,121406.25,150.695414
1,2025-08-11T10:00:00+00:00,BTC-USD,121407.36,121428.76,120926.35,121150.11,106.300777
2,2025-08-11T11:00:00+00:00,BTC-USD,121150.10,121252.87,120248.43,120525.00,257.085550
3,2025-08-11T12:00:00+00:00,BTC-USD,120525.00,120650.65,119505.00,119616.96,395.203193
4,2025-08-11T13:00:00+00:00,BTC-USD,119620.83,120313.40,119333.35,119976.39,436.222052

In [28]:
df.describe()

                open           high            low          close       volume
count    8750.000000    8750.000000    8750.000000    8750.000000  8750.000000
mean    84958.969683   85214.016403   84685.712786   84952.374719   341.625402
std     18997.061748   19024.514460   18961.407781   18994.346881   380.425270
min     58186.390000   58517.280000   57717.550000   58190.000000     2.744184
25%     67578.802500   67859.757500   67310.995000   67574.687500   128.706014
50%     80022.210000   80249.840000   79721.420000   80016.900000   219.622237
75%    102035.430000  102337.932500  101673.840000  102017.260000   406.789707
max    126099.210000  126296.000000  125319.850000  126099.220000  6239.238189

In [29]:
df.columns[:]

Index(['time', 'symbol', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

In [30]:
df['close'].values

array([121406.25, 121150.11, 120525.  , ...,  63897.94,  63999.16,
        63985.15], shape=(8750,))

### SINCE WE ARE USING RAW DATA WE NEED TO SHIFT OUR DATA SO WE CAN HAVE TARGET VALUES

In [ ]:

df['target_next_close'] = df['close'].shift(-1)
df.dropna() #last row wont have anything

,time,symbol,open,high,low,close,volume,target_next_close
0,2025-08-11T09:00:00+00:00,BTC-USD,121662.15,121703.75,121094.37,121406.25,150.695414,121150.11
1,2025-08-11T10:00:00+00:00,BTC-USD,121407.36,121428.76,120926.35,121150.11,106.300777,120525.00
2,2025-08-11T11:00:00+00:00,BTC-USD,121150.10,121252.87,120248.43,120525.00,257.085550,119616.96
3,2025-08-11T12:00:00+00:00,BTC-USD,120525.00,120650.65,119505.00,119616.96,395.203193,119976.39
4,2025-08-11T13:00:00+00:00,BTC-USD,119620.83,120313.40,119333.35,119976.39,436.222052,120222.41
...,...,...,...,...,...,...,...,...
8744,2026-08-11T03:00:00+00:00,BTC-USD,63978.06,64118.95,63978.06,64074.72,100.259653,63960.21
8745,2026-08-11T04:00:00+00:00,BTC-USD,64074.71,64095.91,63956.58,63960.21,88.774600,63926.89
8746,2026-08-11T05:00:00+00:00,BTC-USD,63960.21,63992.19,63881.73,63926.89,79.994356,63897.94
8747,2026-08-11T06:00:00+00:00,BTC-USD,63926.90,63986.16,63783.21,63897.94,87.796354,63999.16
8748,2026-08-11T07:00:00+00:00,BTC-USD,63897.94,64049.29,63836.55,63999.16,89.758020,63985.15

In [10]:
df.describe()

,open,high,low,close,volume,target_next_close
count,8750.000000,8750.000000,8750.000000,8750.000000,8750.000000,8749.000000
mean,84958.969683,85214.016403,84685.712786,84952.374719,341.625402,84948.208085
std,18997.061748,19024.514460,18961.407781,18994.346881,380.425270,18991.433089
min,58186.390000,58517.280000,57717.550000,58190.000000,2.744184,58190.000000
25%,67578.802500,67859.757500,67310.995000,67574.687500,128.706014,67573.320000
50%,80022.210000,80249.840000,79721.420000,80016.900000,219.622237,80013.530000
75%,102035.430000,102337.932500,101673.840000,102017.260000,406.789707,102012.640000
max,126099.210000,126296.000000,125319.850000,126099.220000,6239.238189,126099.220000

In [11]:
df.columns

Index(['time', 'symbol', 'open', 'high', 'low', 'close', 'volume',
       'target_next_close'],
      dtype='object')

In [15]:
X = df.drop(columns = ["time","symbol","target_next_close"])
y = df['target_next_close']

In [20]:
X.describe(), y.describe()

(                open           high            low          close       volume
 count    8750.000000    8750.000000    8750.000000    8750.000000  8750.000000
 mean    84958.969683   85214.016403   84685.712786   84952.374719   341.625402
 std     18997.061748   19024.514460   18961.407781   18994.346881   380.425270
 min     58186.390000   58517.280000   57717.550000   58190.000000     2.744184
 25%     67578.802500   67859.757500   67310.995000   67574.687500   128.706014
 50%     80022.210000   80249.840000   79721.420000   80016.900000   219.622237
 75%    102035.430000  102337.932500  101673.840000  102017.260000   406.789707
 max    126099.210000  126296.000000  125319.850000  126099.220000  6239.238189,
 count      8749.000000
 mean      84948.208085
 std       18991.433089
 min       58190.000000
 25%       67573.320000
 50%       80013.530000
 75%      102012.640000
 max      126099.220000
 Name: target_next_close, dtype: float64)

In [ ]:
# Here we split form regression to classifier

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,
                                                 train_size=.8,
                                                 random_state=42)

In [31]:
print(y_train.head())

1222    116150.38
6605     79572.29
1315    125136.87
7958     62722.52
2057    101686.79
Name: target_next_close, dtype: float64

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,
                                                 train_size=.8,
                                                 random_state=42)

df['target_up'] = (df['close'].shift(-1) > df['close']).astype(int)
df = df.dropna()

X = df.drop(columns = ["time","symbol","target_up"])
y = df["target_up"]


model = RandomForestClassifier(
        n_estimators=100,
        max_depth=6,
        min_samples_split=10, #n instances of rule then  split
        min_samples_leaf=5, #makes sure t hat the split is good
        random_state=42,
        verbose=1)

model.fit(X_train,y_train)
probabilities = model.predict_proba(X_test)

#up_vote_percentage = probabilities[-1][1]

df_test_results = pd.DataFrame({
    "Actual_Direction": y_test,
    "Model Prediction": probabilities[:,1]
})

print("Sample prediction ")
print(df_test_results.head(10))

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.1s

Sample prediction
      Actual_Direction  Model Prediction
2333                 1          0.483352
2778                 0          0.493805
5035                 0          0.497765
6857                 0          0.497605
6429                 0          0.493185
5318                 1          0.486037
7583                 1          0.558351
7675                 1          0.482088
6328                 0          0.483695
5407                 0          0.482919

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.3s finished
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

In [ ]:
probabilities